apiVersion: apps/v1
kind: Deployment
metadata:
  name: inferno-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inferno-app
  template:
    metadata:
      labels:
        app: inferno-app
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      initContainers:
      - name: run-migrations
        image: {{ .Values.inferno.imageUrl }}
        imagePullPolicy: Always
        command: ["bundle", "exec", "rake", "db:migrate"]
        env:
          - name: TX_SERVER_URL
            value: {{ .Values.inferno.terminologyServer }}
          {{- if .Values.postgresql.enabled }}
          - name: POSTGRES_HOST
            value: "my-inferno-postgresql"
          - name: POSTGRES_DB
            value: {{ .Values.postgresql.global.postgresql.auth.database | quote }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgresql.global.postgresql.auth.password | quote }}
          - name: POSTGRES_USER
            value: {{ .Values.postgresql.global.postgresql.auth.username | quote }}
          - name: POSTGRES_PORT
            value: {{ .Values.postgresql.containerPorts.postgresql | quote }}
          {{- end }}
        envFrom:
        - configMapRef:
            name: inferno
      containers:
      - name: inferno-app
        image: {{ .Values.inferno.imageUrl }}
        imagePullPolicy: Always
        ports:
          - containerPort: 4567
        env:
          - name: TX_SERVER_URL
            value: {{ .Values.inferno.terminologyServer }}
        {{- if .Values.postgresql.enabled }}
          - name: POSTGRES_HOST
            value: "my-inferno-postgresql"
          - name: POSTGRES_DB
            value: {{ .Values.postgresql.global.postgresql.auth.database | quote }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgresql.global.postgresql.auth.password | quote }}
          - name: POSTGRES_USER
            value: {{ .Values.postgresql.global.postgresql.auth.username | quote }}
          - name: POSTGRES_PORT
            value: {{ .Values.postgresql.containerPorts.postgresql | quote }}
          {{- end }}
        envFrom:
        - configMapRef:
            name: inferno

