apiVersion: apps/v1
kind: Deployment
metadata:
  name: inferno-worker
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inferno-worker
  template:
    metadata:
      labels:
        app: inferno-worker
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: inferno-worker
        image: {{ .Values.inferno.imageUrl }}
        command: ["bundle", "exec", "sidekiq", "-r", "./worker.rb"]
        imagePullPolicy: Always
        env:
          {{- if .Values.postgresql.enabled }}
          - name: POSTGRES_HOST
            value: "my-inferno-postgresql"
          - name: POSTGRES_DB
            value: {{ .Values.postgresql.global.postgresql.auth.database | quote }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgresql.global.postgresql.auth.password | quote }}
          - name: POSTGRES_USER
            value: {{ .Values.postgresql.global.postgresql.auth.username | quote }}
          - name: POSTGRES_PORT
            value: {{ .Values.postgresql.containerPorts.postgresql | quote }}
          {{- end }}
        envFrom:
        - configMapRef:
            name: inferno
 
