apiVersion: apps/v1
kind: Deployment
metadata:
  name: inferno-worker
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inferno-worker
  template:
    metadata:
      labels:
        app: inferno-worker
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: inferno-worker
        image: {{ .Values.inferno.imageUrl }}
        command: ["bundle", "exec", "sidekiq", "-r", "./worker.rb"]
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: postgres-database
        - configMapRef:
            name: postgres
        - configMapRef:
            name: inferno
 
