require:
  - rubocop-erb
AllCops:
  Exclude:
    - 'lib/au_core_test_kit/custom_groups/clinical_note_type_test.rb'
    - 'lib/au_core_test_kit/custom_groups/smart_app_launch_group.rb'
    - 'lib/au_core_test_kit/custom_groups/v0.3.0-ballot/capability_statement_group.rb'
    - 'lib/au_core_test_kit/custom_groups/v0.3.0-ballot/profile_support_test.rb'
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Naming/ClassAndModuleCamelCase:
  Enabled: false
