# templates/inferno-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: inferno
  namespace: {{ .Values.namespace }}
data:
  FHIR_RESOURCE_VALIDATOR_URL: {{ default "http://validator-api:4567" .Values.inferno.externalValidatorUrl }}
  REDIS_URL: "redis://inferno-redis:6379"
  RAILS_ENV: "production"
