# templates/postgres-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_HOST: "inferno-postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
