# templates/postgresql-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_HOST: {{ printf "%s-postgresql" .Release.Name | quote }}
  POSTGRES_USER: {{ .Values.postgresql.global.postgresql.auth.username | quote }}
  POSTGRES_PORT: {{ .Values.postgresql.containerPorts.postgresql | quote }}
