# templates/postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-database
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_DB: {{ "inferno" | b64enc }}
  POSTGRES_PASSWORD: {{ randAlphaNum 32 | b64enc }}
