externalDomain: "inferno.hl7.org.au"

inferno:
  imageUrl: "ghcr.io/hl7au/au-fhir-core-inferno:8f99e69b04e98f09cf7815b7b6bdb0d39729523a"
  terminologyServer: "https://tx.dev.hl7.org.au/fhir"
  externalValidatorUrl: null  # This can be overridden during chart deployment

controller:
  enabled: false # Set to true to enable the ingress controller if you have not already installed it, multiple ingress controllers can be installed via https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/
  ingressClass: "nginx"
  ingressClassResource:
    name: nginx
    enabled: true
    default: false
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        
postgresql:
  enabled: false # enable if not using rds from aws-impl
  externaldbhost: null # This can be overridden during chart deployment
  containerPorts:
    postgresql: 5432
  global:
    postgresql:
      auth:
        username: "postgres"
        password: "password"
        database: "inferno"
