apiVersion: v1
kind: Service
metadata:
  name: inferno-postgres
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort ## Change to LoadBalancer or ClusterIP later?
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: inferno-postgres