name: Generate Tests
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make
    - name: Run ig_download
      run: make ig_download
    - name: Run generate
      run: make generate
    - uses: GrantBirki/git-diff-action@v2.6.1
      id: git-diff-action
      with:
        raw_diff_file_output: diff.txt
        file_output_only: "true"
    - name: print raw diff
      env:
        DIFF: ${{ steps.git-diff-action.outputs.raw-diff-path }}
      run: cat $DIFF
