name: Publish Gem
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - name: Rubygems release
      uses: ActionsToolbox/gem-build-and-release-action@master
      env:
        RUBYGEMS_API_KEY: ${{secrets.RUBYGEMSKEY}}
